title: KineticGas
description: A ThermoTools Project
show_downloads: true
theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-feed
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-include-cache

url: 'https://vegardjervell.github.io'
baseurl: '/KineticGas'

data_sources:
  sidebar: "sidebar.md"

includes_dir: _includes

pypi_url: 'https://pypi.org/project/pykingas/'

vcurrent:
  version: 'Latest version (beta)'

  github:
    repository_name: 'ThermoPack'
    owner_name: 'ThermoTools'
    repository_url: 'https://github.com/vegardjervell/thermopack'
    zip_url: 'https://github.com/vegardjervell/thermopack/archive/main.zip'

  pypi:
    url: 'https://pypi.org/project/thermopack/'


defaults:
  -
    scope:
      path: ""
      type: "documentation"
    values:
      layout: "default"